# Site settings
title: GIRITUZE IRADUKUNDA Mireille
url: "http://laobubu.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: your_email@example.com
author: GIRITUZE IRADUKUNDA Mireille
avatar: "https:https://github.com/Mmireillle/Mmireillle.github.io/blob/gh-pages/photos/mireille.JPG?raw=true"
profile: About all you can do in life is be who you are.
#twitter_username: twitter_username
#github_username:  github_username
profile_links: Welcome to my site i hope you will gain something here.
  Email: "mailto:your_mireille.girituze@aims.ac.rw"
  GitHub: "https://github.com/Mmireillle"
  Linkedin: "https://www.linkedin.com/in/girituze-iradukunda-mireille-028456208"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    #Category: /category/
    #Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
